stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed
  model_bulding:
    cmd: python src/model_bulding.py
    deps:
    - data/processed
    - src/model_bulding.py
    outs:
    - model.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - metrics.json
